Make `automerge` default to false
rancher/renovate-config pull request #21
Opened 2023-02-28 14:17 UTC by macedogm

This allows repo owners using the automation to better handle when they want to merge the PRs, specially during code freezes (so we don't need to disable the automation in those periods).

2023-02-28 14:23 UTC, pjbgf submitted a review, later dismissed

2023-02-28 14:30 UTC, superseb requested changes
The default is false, every rule that is only there for automerge should be removed so it defaults to false.

In current form, it seems like the default is true for anything which is not excluded in this config.

2023-02-28 18:40 UTC, macedogm commented
Updated to address Seb's comment.

2023-02-28 19:31 UTC, pjbgf approved these changes

2023-03-01 06:14 UTC, superseb approved these changes
The schedule was created to create PRs and auto merge in the weekend, now it will just create the PRs in the weekend.

2023-03-01 10:36 UTC, merged